# Project 1. HMM 적용하여 데이터 모델링 해보기

## Hidden Markov Model

* https://web.stanford.edu/~jurafsky/slp3/A.pdf
  
## Character Trajactories Data Set
* Import mat-formatted data
  * `mixoutALL_shifted.mat`
* Data Features
  * Data Set Characteristics: Time-Series
  * Number of Instances: 2858
  * Attribute Characteristics: Real
  * Number of Attributes: 3
  * Missing Values? N/A
  * Each character sample is a 3-dimensional pen tip velocity trajectory. This is contained in matrix format, with 3 rows and T columns where T is the length of the character sample.
  * 3 Dimensions were kept - x, y, and pen tip force.
  * http://archive.ics.uci.edu/ml/datasets/Character+Trajectories

In [157]:
from scipy import io
import numpy as np
mat_file = io.loadmat('./mixoutALL_shifted.mat')

# print(mat_file['consts'].dtype)
consts = mat_file['consts'][0,0]
mixouts = mat_file['mixout'][0]

keys = np.squeeze(consts['key'][0])
charlabels = consts['charlabels'][0]

num_keys = key.size
num_mixouts = mixouts.shape[0]

print('num_mixouts:', num_mixouts)
print('num_keys:', num_keys)
for i in range(num_keys):
    print(keys[i], end='')
# print()
# for i in range(len(charlabels)):
#     print(i, charlabels[i])

num_mixouts: 2858
num_keys: 20
['a']['b']['c']['d']['e']['g']['h']['l']['m']['n']['o']['p']['q']['r']['s']['u']['v']['w']['y']['z']

In [147]:
for i in range(num_mixouts):
    mixouts[i] = np.transpose(mixouts[i])
#     print(i, mixouts[i].shape)
    print(mixouts[i])
    break

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.32025216e-02  4.68315970e-02  5.95197370e-01]
 [-5.74907689e-02  5.78597833e-02  7.39801420e-01]
 [-8.56596342e-02  6.32381420e-02  8.23061971e-01]
 [-1.13578523e-01  6.28141740e-02  8.47725762e-01]
 [-1.39034515e-01  5.81903497e-02  8.32962764e-01]
 [-1.62219529e-01  5.13763997e-02  7.98143908e-01]
 [-1.84023319e-01  4.39355058e-02  7.57315120e-01]
 [-2.04616465e-01  3.68195598e-02  7.20023414e-01]
 [-2.23463280e-01  3.02980051e-02  6.90240523e-01]
 [-2.39748278e-01  2.39554361e-02  6.66110400e-01]
 [-2.52434892e-01  1.73626632e-02  6.44920437e-01]
 [-2.60490826e-01  1.09386914e-02  6.26634781e-01]
 [-2.63607659e-01  5.74643741e-03  6.10337107e-01]
 [-2.62712148e-01  2.45148434e-03  5.92130800e-01]
 [-2.59751112e-01  8.35473712e-04  5.70913779e-01]
 [-2.57103618e-01  2.17927862e-04  5.51942181e-01]
 [-2.57071821e-01 -4.89815854e-